"""
REDIRECTED TO views/ PACKAGE

All ViewSets have been moved to the views/ package for better organization.
This file exists only for backward compatibility.

DO NOT EDIT THIS FILE - All code is in views/ package
"""

# Re-export everything from the views package
from .views import (  # noqa: F401
    get_client_ip,
    PropertyViewSet,
    AreaViewSet,
    AmenityViewSet,
    OfferViewSet,
    ContactMessageViewSet,
    ActivityLogViewSet,
    DashboardAnalyticsViewSet,
    TransactionViewSet,
    VisitorViewSet,
    NotificationViewSet,
)

__all__ = [
    'get_client_ip',
    'PropertyViewSet',
    'AreaViewSet',
    'AmenityViewSet',
    'OfferViewSet',
    'ContactMessageViewSet',
    'ActivityLogViewSet',
    'DashboardAnalyticsViewSet',
    'TransactionViewSet',
    'VisitorViewSet',
    'NotificationViewSet',
]
