"""
REDIRECTED TO views/ PACKAGE

All ViewSets have been moved to the views/ package for better organization.
This file exists only for backward compatibility.

DO NOT EDIT THIS FILE - All code is in views/ package

Import all ViewSets from the views package:
"""

# Re-export everything from the views package
from .views import *  # noqa: F401, F403

__all__ = [
    'PropertyViewSet',
    'AreaViewSet',
    'OfferViewSet',
    'ContactMessageViewSet',
    'ActivityLogViewSet',
    'DashboardAnalyticsViewSet',
    'TransactionViewSet',
    'VisitorViewSet',
    'get_client_ip',
]
