# Generated by Django 5.2.7 on 2026-02-16 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(help_text='اسم العقار الذي تم منه الربح', max_length=255, verbose_name='اسم العقار')),
                ('area', models.CharField(help_text='منطقة العقار', max_length=255, verbose_name='المنطقة')),
                ('property_type', models.CharField(choices=[('students', 'طلاب'), ('families', 'عائلات'), ('vacationers', 'مصيفين'), ('studio', 'استديو'), ('daily', 'حجز يومي')], default='families', max_length=50, verbose_name='نوع العقار')),
                ('earnings', models.DecimalField(decimal_places=2, help_text='قيمة الربح بالجنيه المصري', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الأرباح')),
                ('deal_date', models.DateField(help_text='التاريخ الذي تمت فيه الصفقة', verbose_name='تاريخ الصفقة')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية عن الصفقة', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'أرباح المستخدم',
                'verbose_name_plural': 'أرباح المستخدمين',
                'ordering': ['-deal_date', '-created_at'],
                'indexes': [models.Index(fields=['-deal_date'], name='earnings_us_deal_da_038ea4_idx'), models.Index(fields=['user', '-deal_date'], name='earnings_us_user_id_e60c44_idx')],
            },
        ),
    ]
