# Generated by Django 5.1.3 on 2026-01-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="property",
            name="type",
        ),
        migrations.RemoveField(
            model_name="property",
            name="type_en",
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "شقة"),
                    ("villa", "فيلا"),
                    ("studio", "استوديو"),
                    ("duplex", "دبلكس"),
                    ("townhouse", "تاونهاوز"),
                ],
                max_length=50,
            ),
        ),
    ]
