# Generated by Django 5.1.3 on 2026-01-03 00:41

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0002_remove_property_description_en_remove_property_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="property_type",
        ),
        migrations.AddField(
            model_name="property",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="property",
            name="type_en",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.UUIDField(
                default=listings.models.generate_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
