# Generated by Django 6.0 on 2026-01-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_property_property_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="usage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("students", "طلاب"),
                    ("families", "عائلات"),
                    ("studio", "استوديو"),
                    ("vacation", "مصيفين"),
                    ("daily", "حجز يومي"),
                ],
                max_length=20,
            ),
        ),
    ]
