# Generated by Django 5.2.7 on 2026-01-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_set_default_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='type_en',
        ),
    ]
