# Generated by Django 5.2.7 on 2026-01-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_area_name_en_remove_property_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='listings.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
    ]
