# Generated by Django 5.2.7 on 2026-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_property_address_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
