# Generated by Django 5.2.7 on 2026-01-19 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_property_contact_alter_property_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
