# Generated by Django 5.2.7 on 2026-01-19 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_property_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[0-9]+$', 'رقم التواصل يجب أن يحتوي على أرقام فقط')]),
        ),
    ]
