# Generated by Django 5.2.7 on 2026-01-22 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_property_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('target_audience', models.CharField(choices=[('students', 'طلاب'), ('families', 'عائلات'), ('all', 'الجميع')], default='all', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('icon_type', models.CharField(choices=[('graduation', 'تخرج'), ('gift', 'هدية'), ('star', 'نجمة'), ('sparkles', 'براق')], default='sparkles', max_length=50)),
                ('terms', models.TextField(blank=True, help_text='شروط العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-created_at'],
            },
        ),
    ]
