# Generated by Django 5.2.7 on 2026-01-22 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
