# Generated by Django 5.2.7 on 2026-01-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_offer_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='اتركه فارغاً للعرض الدائم', null=True),
        ),
    ]
