# Generated by Django 5.2.7 on 2026-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_offer_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='target_audience',
            field=models.CharField(choices=[('students', 'طلاب'), ('families', 'عائلات'), ('studio', 'استوديو'), ('daily', 'حجز يومي'), ('rooms', 'غرف'), ('all', 'الجميع')], default='all', max_length=50),
        ),
    ]
