# Generated by Django 5.2.7 on 2026-01-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_offer_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='terms',
        ),
    ]
