# Generated by Django 5.2.7 on 2026-01-22 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_offer_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
