# Generated by Django 5.2.7 on 2026-01-22 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_property_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='terms',
            field=models.TextField(blank=True, help_text='شروط العرض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='نسبة الخصم من 0 إلى 100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
