# Generated by Django 5.2.7 on 2026-01-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_offer_terms_alter_property_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='discount_percentage',
        ),
    ]
