# Generated by Django 5.2.7 on 2026-01-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_contactmessage_remove_property_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
    ]
