# Generated by Django 5.2.7 on 2026-01-24 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_remove_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[0-9]+$', 'رقم التواصل يجب أن يحتوي على أرقام فقط')]),
        ),
    ]
