# Generated by Django 5.2.7 on 2026-01-25 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر الأصلي'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[0-9]+$', 'رقم التواصل يجب أن يحتوي على أرقام فقط')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول'),
        ),
    ]
