# Generated by Django 5.2.7 on 2026-01-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_property_discount_property_original_price_and_more'),
        ('users', '0013_remove_userprofile_detailed_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_property', 'إضافة عقار جديد'), ('delete_property', 'حذف عقار'), ('update_property', 'تعديل عقار'), ('create_user', 'إنشاء حساب جديد'), ('approve_property', 'الموافقة على عقار'), ('reject_property', 'رفض عقار')], max_length=50, verbose_name='نوع النشاط')),
                ('content_type', models.CharField(choices=[('property', 'عقار'), ('user', 'مستخدم')], max_length=50, verbose_name='نوع المحتوى')),
                ('object_id', models.CharField(blank=True, max_length=500, verbose_name='معرف الكائن')),
                ('object_name', models.CharField(blank=True, max_length=500, verbose_name='اسم الكائن')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='users.userprofile', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='listings_ac_timesta_7b1e7e_idx'), models.Index(fields=['user', '-timestamp'], name='listings_ac_user_id_9c81b7_idx'), models.Index(fields=['action', '-timestamp'], name='listings_ac_action_4b9198_idx')],
            },
        ),
    ]
