# Generated by Django 5.2.7 on 2026-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='browser_name',
            field=models.CharField(default='غير معروف', max_length=255, verbose_name='متصفح'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='city',
            field=models.CharField(default='غير معروف', max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country',
            field=models.CharField(default='غير معروف', max_length=100, verbose_name='البلد'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='device_name',
            field=models.CharField(default='غير معروف', max_length=255, verbose_name='اسم الجهاز'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'موبايل'), ('desktop', 'سطح المكتب'), ('tablet', 'جهاز لوحي')], default='desktop', max_length=20, verbose_name='نوع الجهاز'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='os_name',
            field=models.CharField(default='غير معروف', max_length=255, verbose_name='نظام التشغيل'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='province',
            field=models.CharField(default='غير معروف', max_length=100, verbose_name='المحافظة'),
        ),
    ]
