# Generated by Django 5.2.7 on 2026-01-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_activitylog_browser_name_activitylog_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='browser_name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='city',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='country',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='os_name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='province',
        ),
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='property',
            name='visitors',
            field=models.IntegerField(default=0, verbose_name='عدد الزيارات'),
        ),
    ]
