# Generated by Django 5.2.7 on 2026-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_remove_activitylog_browser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visited_ips',
            field=models.JSONField(blank=True, default=dict, verbose_name='IP Addresses التي زارت العقار'),
        ),
    ]
