# Generated by Django 5.2.7 on 2026-01-28 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_property_visited_ips'),
        ('users', '0013_remove_userprofile_detailed_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_properties', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='هل تم الحذف'),
        ),
    ]
