# Generated by Django 5.2.7 on 2026-01-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_property_deleted_at_property_deleted_by_and_more'),
        ('users', '0013_remove_userprofile_detailed_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_properties', to='users.userprofile', verbose_name='تم الحذف بواسطة'),
        ),
    ]
