# Generated by Django 5.2.7 on 2026-01-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_alter_property_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشفة'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروءة'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='الموضوع'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at'], name='listings_co_created_b9af44_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', '-created_at'], name='listings_co_is_read_a5dab5_idx'),
        ),
    ]
