# Generated by Django 5.2.7 on 2026-01-29 18:08

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_notification'),
        ('users', '0013_remove_userprofile_detailed_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=listings.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=200, verbose_name='اسم العقار')),
                ('region', models.CharField(max_length=100, verbose_name='المنطقة')),
                ('account_type', models.CharField(choices=[('owner', 'مالك'), ('agent', 'وسيط'), ('office', 'مكتب عقارات'), ('tenant', 'مستأجر')], max_length=20, verbose_name='نوع الحساب')),
                ('property_type', models.CharField(choices=[('students', 'طلاب'), ('families', 'عائلات'), ('studio', 'استوديو'), ('vacation', 'مصيفين'), ('daily', 'حجز يومي')], max_length=20, verbose_name='نوع العقار')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الإيجار')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='العمولة')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الربح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.userprofile', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صفقة',
                'verbose_name_plural': 'الصفقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='listings_tr_created_735607_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='listings_tr_user_id_f3700b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_type', '-created_at'], name='listings_tr_account_6548c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['property_type', '-created_at'], name='listings_tr_propert_983c7c_idx'),
        ),
    ]
