# Generated by Django 5.2.7 on 2026-01-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_transaction_delete_notification_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='listings_tr_propert_983c7c_idx',
        ),
    ]
