# Generated by Django 5.2.7 on 2026-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_remove_transaction_listings_tr_propert_983c7c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='بيانات المتصفح')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('visit_count', models.IntegerField(default=1, verbose_name='عدد الزيارات')),
                ('last_visited', models.DateTimeField(auto_now=True, verbose_name='آخر زيارة')),
                ('first_visited', models.DateTimeField(auto_now_add=True, verbose_name='أول زيارة')),
            ],
            options={
                'verbose_name': 'زائر',
                'verbose_name_plural': 'الزوار',
                'ordering': ['-last_visited'],
                'indexes': [models.Index(fields=['ip_address'], name='listings_vi_ip_addr_b7df56_idx'), models.Index(fields=['-last_visited'], name='listings_vi_last_vi_76f0c9_idx')],
            },
        ),
    ]
