# Generated by Django 5.2.7 on 2026-01-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'هاتف'), ('tablet', 'تابلت'), ('desktop', 'كمبيوتر'), ('unknown', 'غير معروف')], default='unknown', max_length=20, verbose_name='نوع الجهاز'),
        ),
    ]
