# Generated by Django 5.2.7 on 2026-01-30 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_visitor_device_type'),
        ('users', '0013_remove_userprofile_detailed_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('delete', 'حذف'), ('restore', 'استرجاع'), ('approve', 'موافقة'), ('reject', 'رفض')], max_length=20, verbose_name='نوع العملية')),
                ('property_data_before', models.JSONField(blank=True, default=dict, verbose_name='بيانات العقار قبل العملية')),
                ('property_data_after', models.JSONField(blank=True, default=dict, verbose_name='بيانات العقار بعد العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات/السبب')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_audit_logs', to='users.userprofile', verbose_name='تم بواسطة')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='listings.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'سجل تدقيق العقار',
                'verbose_name_plural': 'سجلات تدقيق العقارات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['property', '-timestamp'], name='listings_pr_propert_25d053_idx'), models.Index(fields=['-timestamp'], name='listings_pr_timesta_4c8243_idx'), models.Index(fields=['action', '-timestamp'], name='listings_pr_action_290725_idx'), models.Index(fields=['performed_by', '-timestamp'], name='listings_pr_perform_13f93f_idx')],
            },
        ),
    ]
