# Generated by Django 5.2.7 on 2026-01-31 12:54

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_propertyaudittrail'),
        ('users', '0013_remove_userprofile_detailed_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=listings.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('property', 'عقار جديد'), ('message', 'رسالة جديدة'), ('user', 'مستخدم جديد'), ('view', 'مشاهدات عالية'), ('approval', 'موافقة على عقار'), ('rejection', 'رفض عقار')], max_length=50, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('is_read', models.BooleanField(default=False, verbose_name='هل تم القراءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile', verbose_name='المستقبل')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.property', verbose_name='العقار المتعلق')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='users.userprofile', verbose_name='المستخدم المتعلق')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='listings_no_recipie_fed949_idx'), models.Index(fields=['recipient', 'is_read'], name='listings_no_recipie_21cbea_idx')],
            },
        ),
    ]
