# Generated by Django 5.2.7 on 2026-02-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
    ]
