# Generated by ChatGPT on 2026-02-01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0045_property_approved_at_property_rejected_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="property",
            name="rejected_at",
        ),
    ]
