# Generated by Django 5.2.7 on 2026-02-03 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_property_approved_at_property_rejected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم (%)'),
        ),
    ]
