# Generated by Django 5.2.7 on 2026-02-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_alter_property_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر اليومي'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('property', 'عقار جديد'), ('message', 'رسالة جديدة'), ('user', 'مستخدم جديد'), ('view', 'مشاهدات عالية'), ('rejection', 'رفض عقار')], max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر (شهري)'),
        ),
    ]
