# Generated by Django 5.2.7 on 2026-02-15 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_property_daily_price_and_more'),
        ('users', '0014_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الميزة')),
                ('icon', models.CharField(choices=[('wind', 'تكييف مركزي'), ('coffee', 'مطبخ مجهز'), ('wifi', 'إنترنت فائق السرعة'), ('car', 'موقف سيارات'), ('shield', 'أمن 24 ساعة'), ('dooropen', 'مصعد'), ('droplets', 'غسالة ملابس'), ('tv', 'تلفزيون ذكي'), ('sofa', 'أثاث'), ('bath', 'حمام نظيف'), ('washing', 'آلة غسيل'), ('microwave', 'ميكروويف'), ('fridge', 'ثلاجة'), ('ac', 'مكيف هواء'), ('heater', 'دفاية'), ('balcony', 'شرفة'), ('garden', 'حديقة'), ('parking', 'موقف سيارات خاص'), ('gym', 'صالة رياضية'), ('pool', 'حمام السباحة')], max_length=20, verbose_name='رمز الميزة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الميزة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديث')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'المميزات',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=300, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الموافقة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to='users.userprofile', verbose_name='موافق عليه من'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='listings.area', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='عدد الحمامات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.IntegerField(default=1, verbose_name='عدد الأسرة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[0-9]+$', 'رقم التواصل يجب أن يحتوي على أرقام فقط')], verbose_name='رقم التواصل'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_properties', to='users.userprofile', verbose_name='محذوف بواسطة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='مفروش'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.userprofile', verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الشهري'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=1, verbose_name='عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(verbose_name='المساحة (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='property',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('students', 'طلاب'), ('families', 'عائلات'), ('studio', 'استوديو'), ('vacation', 'مصيفين'), ('daily', 'حجز يومي')], max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='property',
            name='visited_ips',
            field=models.JSONField(blank=True, default=dict, verbose_name='عناوين IP التي زارت العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='visitors',
            field=models.IntegerField(default=0, verbose_name='عدد الزيارات الفريدة'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='listings.amenity', verbose_name='المميزات والخدمات'),
        ),
    ]
