# Generated by Django 5.2.7 on 2026-02-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_alter_amenity_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(choices=[('wind', 'تكييف مركزي'), ('coffee', 'مطبخ مجهز'), ('wifi', 'إنترنت فائق السرعة'), ('car', 'موقف سيارات'), ('shield', 'أمن 24 ساعة'), ('dooropen', 'مصعد'), ('droplets', 'غسالة ملابس'), ('tv', 'تلفزيون ذكي'), ('sofa', 'أثاث'), ('bath', 'حمام نظيف'), ('washing', 'آلة غسيل'), ('microwave', 'ميكروويف'), ('fridge', 'ثلاجة'), ('ac', 'مكيف هواء'), ('heater', 'دفاية'), ('balcony', 'شرفة'), ('garden', 'حديقة'), ('parking', 'موقف سيارات خاص'), ('gym', 'صالة رياضية'), ('pool', 'حمام السباحة'), ('zap', 'عداد كهرباء كارت'), ('water_card', 'عداد مياه كارت'), ('receipt', 'عداد مياه فاتورة'), ('thermometer', 'سخان مياه'), ('filter', 'فلتر مياه'), ('flame', 'غاز طبيعي'), ('bottle', 'غاز بومبة')], max_length=20, verbose_name='رمز الميزة'),
        ),
    ]
