# Generated by Django 5.2.7 on 2026-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0054_alter_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='original_contact',
            field=models.CharField(blank=True, help_text='رقم التواصل الذي تم إدخاله عند إنشاء العقار (لا يتغير)', max_length=15, null=True, verbose_name='رقم التواصل الأصلي'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(choices=[('wind', 'تكييف مركزي'), ('coffee', 'مطبخ مجهز'), ('wifi', 'إنترنت فائق السرعة'), ('car', 'موقف سيارات'), ('shield', 'أمن 24 ساعة'), ('dooropen', 'مصعد'), ('droplets', 'غسالة ملابس'), ('tv', 'تلفزيون ذكي'), ('sofa', 'أثاث'), ('bath', 'حمام نظيف'), ('washing', 'آلة غسيل'), ('microwave', 'ميكروويف'), ('fridge', 'ثلاجة'), ('ac', 'مكيف هواء'), ('heater', 'دفاية'), ('balcony', 'شرفة'), ('garden', 'حديقة'), ('parking', 'موقف سيارات خاص'), ('gym', 'صالة رياضية'), ('pool', 'حمام السباحة'), ('zap', 'عداد كهرباء كارت'), ('water_card', 'عداد مياه كارت'), ('receipt', 'عداد كهرباء فاتورة'), ('thermometer', 'سخان مياه'), ('filter', 'فلتر مياه'), ('flame', 'غاز طبيعي'), ('bottle', 'اسطوانة غاز')], max_length=20, verbose_name='رمز الميزة'),
        ),
    ]
