# Generated by Django 5.2.7 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0055_property_original_contact_alter_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم العميل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_phone',
            field=models.CharField(default='', max_length=30, verbose_name='رقم هاتف العميل'),
            preserve_default=False,
        ),
    ]
