# Generated by Django 5.2.7 on 2026-03-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0056_transaction_customer_fields'),
        ('users', '0016_remove_passwordresettoken_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحجز'),
        ),
        migrations.AddField(
            model_name='property',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_properties', to='users.userprofile', verbose_name='محجوز بواسطة'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='محجوز'),
        ),
    ]
