# Generated by Django 5.2.7 on 2026-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0057_add_booking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booking_expires_at',
            field=models.DateTimeField(blank=True, help_text='عند انتهاء هذا الموعد سيتم تفعيل حالة محجوز', null=True, verbose_name='موعد انتهاء العد التنازلي للحجز'),
        ),
    ]
