# Generated by Django 5.2.7 on 2026-03-21 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0058_property_booking_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_countdown_hours', models.PositiveIntegerField(default=48, help_text='المدة الافتراضية للعد التنازلي عند بدء الحجز (بالساعات)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='مدة العد التنازلي الافتراضية (ساعات)')),
                ('auto_confirm_on_expire', models.BooleanField(default=True, help_text='هل يتم تأكيد الحجز تلقائياً عند انتهاء مدة العد التنازلي', verbose_name='تأكيد تلقائي عند انتهاء العد')),
                ('send_notification_on_expire', models.BooleanField(default=True, help_text='هل يتم إرسال إشعار للمالك عند تفعيل الحجز تلقائياً', verbose_name='إرسال إشعار عند انتهاء العد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الحجز',
                'verbose_name_plural': 'إعدادات الحجز',
            },
        ),
    ]
