# Generated by Django 5.2.7 on 2026-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0059_bookingsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSettings',
        ),
        migrations.AlterField(
            model_name='property',
            name='booking_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية الحجز (العداد التنازلي)'),
        ),
    ]
