# Generated by Django 5.2.7 on 2026-03-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0060_delete_bookingsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='booking_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية الحجز'),
        ),
    ]
