# Generated by Django 5.2.7 on 2026-03-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0061_alter_property_booking_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booking_duration_hours',
            field=models.IntegerField(default=48, verbose_name='مدة الحجز بالساعات'),
        ),
    ]
