# Generated by Django 5.2.7 on 2026-03-21 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0062_property_booking_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='booking_duration_hours',
        ),
        migrations.RemoveField(
            model_name='property',
            name='booking_expires_at',
        ),
        migrations.AddField(
            model_name='property',
            name='countdown_duration',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة العرض (بالأيام)'),
        ),
        migrations.AddField(
            model_name='property',
            name='countdown_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بداية العد التنازلي'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_limited',
            field=models.BooleanField(default=False, verbose_name='عرض محدود'),
        ),
    ]
