# Generated by Django 5.2.7 on 2026-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprofile_detailed_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('agent', 'Agent'), ('office', 'Office'), ('admin', 'Admin')], default='landlord', max_length=20),
        ),
    ]
