# Generated by Django 5.2.7 on 2026-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='حساب موثّق'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('agent', 'Agent'), ('office', 'Office'), ('admin', 'Admin'), ('tenant', 'Tenant')], default='landlord', max_length=20),
        ),
    ]
